import type { Metadata } from "next";
import "./globals.css";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import "aos/dist/aos.css";

//adding i18n
import { NextIntlClientProvider } from "next-intl";
import { getLocale, getMessages } from "next-intl/server";
import Wrapper from "./wrapper";
import HTMLContent from "./htmlcontent";

export const metadata: Metadata = {
  title: "SFB",
  description: "Generated by SFB",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // side is the easiest way to get started
  const messages = await getMessages();

  return (
    <Wrapper>
      <NextIntlClientProvider messages={messages}>
        <HTMLContent>{children}</HTMLContent>
      </NextIntlClientProvider>
    </Wrapper>
  );
}
