import type { Metadata } from "next";
import { MainLayout } from "@/layout";
import { Mulish, FontCatchyMelody } from "@/resources/font";

import "./globals.css";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${Mulish.variable} ${Mulish.className} ${FontCatchyMelody.variable} ${FontCatchyMelody.className} bg-[#F9F9F9]`}
      >
        <MainLayout>
          {children}
        </MainLayout>
      </body>
    </html>
  );
}
